### ISSUE TITLE
Passport Authenticate function is not working

### ISSUE THREAD

**Issue by SHAPPY0** [hokaccha/node-jwt-simple#54]
Hi all,
I am creating token using `jwt-simple` node module at the time of login.
below is my code:

    apiRoutes.put('/login', function(req, res, next){
      User.findOne({email:req.body.email}, function(err, user){
        bcrypt.compare(req.body.password, user.password, function(err, result){
           if(result){
            var token=jwt.encode(user,config.secret);
            return res.json({token:token});         
          }else{
            return res.json("Incorrect Email and Password")
          }
        })
      })
    });
   

Token is creating successfully.
Now I am trying to authenticate the user in `/dashboard` route.
 

    apiRoutes.get('/dashboard', passport.authenticate('jwt', { session: false}), function(req, res) { 
        var token=getToken(req.headers);
      if(token){
        var decode=jwt.decode(token, config.secret);
        User.findOne({name:decode.name}, function(err, user){
          if(err){res.json(err)}
            if(!user){
              return res.status(403).send({success:false, msg:'Authentication Failed'})
            }else{
              res.json({success:true, msg:'Welcome in the Area' +user.name+'!'})
            }
        })
      }else{
        return res.status(403).send({success:false, msg:'No Token Found'})
      }
      
      });
 

    getToken = function (headers) {
          if (headers && headers.authorization) {
            var parted = headers.authorization.split(' ');
            if (parted.length === 2) {
              return parted[1];
            } else {
              return null;
            }
          } else {
            return null;
          }
        };

Issue is that, when I am hitting this API on `postman` its showing `Unauthorized` and when I remove passport authentication function `passport.authenticate('jwt', { session: false})` from the route then its printing `success:false, msg:'No Token Found'`.
I don't know how to fix this problem. Please have a look at my code and let me know where is my fault.

Help appreciated.
Thanks

**Comment by maotora** [comment]
Hi, @SHAPPY0 .

I have the exact same problem. Lets try to ask on stackoverflow and see if there is any response.
I'm using `koa` and i also tried to `console.log` the decoded token in `passport-jwt` and got something different from my `user._id` which was the token payload.

I also tried to decode the token in someother route without using `passport-jwt` middleware and i kept on getting `Not enough or too many segments` while my token is correct and it just has 3 segments length after split as explained [here](http://stackoverflow.com/a/40390469/2405689).

I'm now planning to post a thread there and see if i'll get a solution. Will give link here too incase someone else falls into this.

**Comment by SHAPPY0** [comment]
Hi @maotora .
I solved this issue by changing in getToken function like below.
 
getToken = function (headers) { 
if (headers && headers.authorization) { 
return headers.authorization; 
} else { 
return null; 
} 
};

and now API  code for user Authenticate is below
 
  apiRoutes.get('/authentication',function(req, res) {
  var token=getToken(req.headers); 
  console.log("/auth" +token); 
  if(token){
    var decode=jwt.decode(token, config.secret); 
    User.findOne({name:decode.name}, function(err, user){
      if(err){res.json(err)}
        if(!user){
          return res.send({success:false, msg:'Authentication Failed'})
        }else{
          res.json(user);
        }
    })
  }else{
    return res.json({success:false, msg:'No Token Found'})
  } 
  });

getToken = function (headers) { 
if (headers && headers.authorization) { 
return headers.authorization; 
} else { 
return null; 
} 
};

**Comment by maotora** [comment]
@SHAPPY0 From your code i got an idea to `jwt.decode(token, secret)` and see if it is the `userId` and it proved not to be.

First it threw a verification error so i had to (*In a different route*) `jwt.decode(token, secret, true)` to disallow verification and this brought back **modified userId** which my app don't recognize.

I'm not sure how it got changed and how i can fix this, but at least a different error.

**Comment by SHAPPY0** [comment]
Can u try without KOA????
Try once using this passport-jwt-strategy

var JwtStrategy   =require('passport-jwt').Strategy;
ExtractJwt = require('passport-jwt').ExtractJwt;
var User          =require('../app/models/usermodel');
var config        =require('../config/database');

module.exports=function(passport){
    var opts = {}; 
    opts.jwtFromRequest = ExtractJwt.fromAuthHeader();
  opts.secretOrKey = config.secret;
  passport.use(new JwtStrategy(opts, function(jwt_payload, done) {
    User.findOne({_id: jwt_payload.id}, function(err, user) {
          if (err) {
              return done(err, false);
          }
          if (user) {
              done(null, user); 
          } else {
              done(null, false);
          }
      });
  }));
};

**Comment by maotora** [comment]
It worked!

I was doing something very wrong without noticing.

I passed a hardcorded `authorization` key on postman and i naively thought that the server will update the headers of postman (*Imagine that!*)

So the request was always passed with an outdated authorization key and it kept on failing.

I also didn't know something very important, that tokens are returned so to be used in xhr (ajax calls if you will) requests.

I thought they will be returned (kinda like how `render` works) and will be placed on the browser headers magically!

Thank you @SHAPPY0 most of what you kept on telling me, pushed me to think harder and harder until i understood this.

**Comment by alexjab** [comment]
Hi, both of you, glad you could solve the issue you encountered.

I jump in the conversation a bit late (I was on the road), but here is a couple of thoughts and advice about your problem and the code you provided:
 - I felt like the problems you described has little to do with `jwt-simple`,
 - do not forget that `jwt.decode` *throws* errors if the token is invalid, so you should update your code in order to handle this case, if you haven't done it already (like adding a `try...catch` or a error handler),
 - decoding a token in the route controller is usually not a very good idea (not the purpose of a controller), you should put it in a reusable function and pass it as a route middleware,
 - your controllers are small but they already show signs of callback hell, you should consider using a control flow module such as `co` or `async/await` (with node 7),
 - your `/login` route returns the whole user in the token (including the hashed password): that is not very good (you don't need the whole user, only their `name`), and even if the user password is hashed, that just does not look like a good idea to return it; also using only the information you need in the token will reduce its size,
 - also, maybe add an expiration (`exp`) field, because having infinite tokens is not good either,
 - also, I think you should identify your user not by their `name`, but by their `_id` (they are always indexed by default, so you don't have to create an additional index just for this).

Again, sorry for not jumping in sooner, and glad that you could resolve your issues.

**Comment by SHAPPY0** [comment]
Hi @alexjab,
Thanks for your suggestions. I will do what ever you told us. If there will be any issue then I will get back to you.

**Comment by alexjab** [comment]
Hi both,

this issue has been opened for quite some time right now, and has not been really active since then. If this is ok for you, I'd like to close it.

Thank you,

Alex

**Comment by alexjab** [comment]
I'm closing the issue, feel free to re-open it if you need anything else.
