### ISSUE TITLE
Make JWT one-time use?

### ISSUE THREAD

**Issue by web-surfer** [hokaccha/node-jwt-simple#63]
I'm using JWT-simple to help make a confirmation email. That is to say, when a user registers for an account, they are sent an email, where they need to click a button to confirm their email address. On click, a URL with the JWT is sent to my server.

My question is: is there a way to make the JWT one-time use? As in, have it expire after the JWT has been sent to the server once?

**Comment by alexjab** [comment]
Hi, I've also implemented a jwt-based email validation. Here is how I did it:
 - when the user signs up, they are created in my db with a field `state: pending` (or anything like that),
 - then, an email is sent to the user containing an url with a JWT (generated using a key different from the one that generates authentication tokens); this token has a short (minutes or hours) expiration date, and contains the user id and the user email,
 - when the user clicks on the link, the server checks the _email_ token (the user needs to be authenticated, and the auth token is checked as usual), and the field `state` in the db is set to `verified` (or something similar) if the decoding works,
 - if the state of the user is already `verified` or the token is invalid, then the controller returns an error.

Regarding the one-time use, JWT are stateless so that's not possible unless you somehow implement a server-side check (like in my example). You can use the `jti` claim (that is give your token a unique identifier, which might help you do so), but I don't think that it is required in your case.

Regarding expiration, same answer, if you need per-token invalidation, you need to d it server-side. In any case, you should add an `exp` (date-based expiration) claim to all of your tokens.

**Comment by web-surfer** [comment]
Thank you for all that. This is roughly how I was going to set my email verification up, and your explanation cleared up some minor points for me.

**Comment by alexjab** [comment]
Hi,

has your question been fully answered so far ? If so, may I close this issue ?

Thank you.

**Comment by alexjab** [comment]
I'm closing the issue, feel free to re-open it if you need anything else.
