### ISSUE TITLE
Version of OpenSSL JWT is using under the hood has a lot of trouble with RSA Key Pair Formats

### ISSUE THREAD

**Issue by cbartondock** [hokaccha/node-jwt-simple#68]
I keep getting the following error:

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:283:26)
    ...

I am creating the key pair as follows: 
`openssl genrsa -out private.pem 2048`
`openssl rsa -in private.pem -pubout -outform PEM -out public.pem`

using them in a simple test via:
`var data_asym_encrypted=jwt.encode(data, fs.readFileSync('./public.pem','utf8'),'RS256');`
`var data_asym_decrypted = jwt.decode(data_asym_encrypted, fs.readFileSync('/.private.pem','utf8'),'RS256');`

I was initially storing them as environment variables and was getting this error, so I've stripped out that layer of complexity for the moment. I'm not convinced that this isn't a problem with the way I am generating my key pair, but I also think it might be an issue with the way jwt handles it.

**Comment by alexjab** [comment]
Hi @cbartondock ,

There are a couple of mistakes in your code that prevent it from running:
1/ you used a public key to encode a token, an then a private key to decode it. It should be the opposite, the private key should encode, and the public should decode,
2/ The path for the private key is invalid, it should be `./private.pem`,
3/ The third argument for `decode` should be `false` if you need to specify an algorithm, which you do here, and then the algorithm.

Correct these three mistakes, and it should work as expected !

BR,

Alex

**Comment by oxygen** [comment]
@alexjab
_you used a public key to encode a token, an then a private key to decode it. It should be the opposite, the private key should encode, and the public should decode,_

Dude :)
Public keys encode, private key decodes.

It is also common sense!!! How could the public key (the one that everyone knows) decode the stuff you are trying to protect?

**Comment by alexjab** [comment]
Well, you are not *protecting* data, you are **validating** it. All the data you are sending in JWTs is in clear-text anyway (it's just base64).

Here is how it works:
 - upon successful connection, the server encodes a token using the private key. It needs to be the private key so that no-one can impersonate the server and issue forged tokens,
 - when the client needs to authenticate, they send the token to the server which **validates** it, using the public key. This means, that any server with your public key can authenticate a user, which is quite useful when having a distributed architecture. If a malicious third-party wants to authenticate a token, it does not do them any good since everything is sent in clear-text anyway.

Here is more information: https://stackoverflow.com/a/39239395

As an advice for participating in open source discussions, you should be a little more *professional* when writing comments, because `It is also common sense!!!`, can be both insulting and false.

BR,

Alex

**Comment by oxygen** [comment]
Here's a professional vocabulary lesson, so we can communicate:

I think by "encode" you mean hashing, not encryption. So you mean signature. JWT has base64 encoding, which has nothing to do with your "private key". The JWT payload is signed and signature is concatenated to the JWT token.

The "private key" you are problably referring to is commonly known as a salt. Salts are the secret stuff when hashing (signing) stuff.

RSA uses the private key for decryption and the public key for encryption. That's why they're called public and private in the first place. If JWT has encryption enabled for **protection** of sensitive data, the that's the way it has to work.

If using RSA to sign stuff, then the private key plays absolutely no role. The public key would be used on both sides on the same payload and it has to arrive at the same result, or the payload would be considered corrupt. Never hear of this usage though. Hashing algorithms exist for a reason.

"Professional" means straight to the point. "Feeling insulted" is not professional. Your appeal to emotions and calling my messages irrelevant is the real problem.

If you would like me to be less professional and cater to your feelings, I will :)

**Comment by oxygen** [comment]
But don't take my word for it, first google search result:

https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-encryption

**Comment by alexjab** [comment]
Right, this module cannot do RSA encryption, only RSA signature.

https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-signature
