### ISSUE TITLE
Logout functionality.

### ISSUE THREAD

**Issue by Lzok** [hokaccha/node-jwt-simple#77]
Helllo guys.
Is there any way to revoke the token before it expires? To implement the logout function.

Thanks!

**Comment by alexjab** [comment]
Hi,

JWTs are stateless and client side, so there is no simple way to "actively" revoke them.

Here are a couple of ways you can do it anyway:
 - add a `jti` (JWT id) claim to your token stored in your backend (db or cache),
 - set a short `exp` claim (the more critical your application, the shorter it should be),
 - every time your client tries to refresh the token (should be around expiration time), check whether the `jti` exists in your db; if it exists, refresh it, if not do not refresh it,
 - when you want to actively revoke the token (when signing off), remove the id from your backend and frontend (so that the client no longer sends the token).

You **should not** check that the token is still valid at every request because that would defeat the purpose of JWTs, but once from time to time is ok (an expiration date of 20 minutes is usually ok). 

Hope it helps,

Alex

**Comment by Lzok** [comment]
@alexjab Thank you for the ideas!
Have a good day.

Closing issue.
